### PR TITLE
PR for merge feature-zhigalko to develop

### PR DESCRIPTION
**Pull request by evzhigalko**
please review my documentation

### CODE REVIEW

**Comment by evzhigalko** [comment]
test

**Review by AleksandrTolkach — APPROVED** [review]
ок

**Review by dyskop — APPROVED** [review]
looks good to me

**Review by IlyaKolbasov — COMMENTED** [review]
everything is good in my opinion!!!

**Review by IlyaKolbasov — APPROVED** [review]
OK

**Review by skarmyzov — APPROVED** [review]
Усе гуд )

**Pull request merged**
